version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/root/persistence/mariadb/mariadb_data:/bitnami'
  joomla:
    image: 'bitnami/joomla:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/root/persistence/httpd/joomla_data:/bitnami'
    environment:
      - JOOMLA_USERNAME=admin
      - JOOMLA_PASSWORD=admin
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  joomla_data:
    driver: local